Run migrations

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,19 +25,25 @@ commands:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
       # Add parameter here     
+      workflow_id:
+        type: string
+        default: ${CIRCLE_WORKFLOW_ID:0:7}
     steps:
       - run:
           name: Revert migrations
           # Add when this will run
+          when: on_fail
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
+            SUCCESS=$(curl -k https://kvdb.io/47dc6uVSZS9kN2uAQ1WKXG/migration_<<workflow_id>>)
             if(( $SUCCESS==1 )); 
             then
-            #  cd ~/project/backend
-            #  npm install
-            #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
+              cd ~/project/backend
+              npm install
+              # Add revert code here. You can find this in the Getting Started section.
+              #npm run build
+              npm run migration:revert
+              # exit 1
             fi
             
 jobs:
@@ -203,7 +209,6 @@ jobs:
     docker:
       # Docker image here that supports Ansible
       - image: python:3.7-alpine3.16
-      # - image: cimg/python:3.10
     steps:
       # Checkout code from git
       - checkout
@@ -229,22 +234,40 @@ jobs:
       # Here's where you will add some code to rollback on failure      
       - destroy-environment
             ##
-            ##  run-migrations:
-            ##    docker:
-            ##      # Docker image here that supports NodeJS
-            ##    steps:
-            ##      # Checkout code from git
-            ##      - run:
-            ##          name: Run migrations
-            ##          command: |
-            ##            # Your code here
-            ##            exit 1
-            ##      - run:
-            ##          name: Send migration results to memstash
-            ##          command: |
-            ##            # Your code here
-            ##            exit 1
-            ##     # Here's where you will add some code to rollback on failure      
+  run-migrations:
+    docker:
+      # Docker image here that supports NodeJS
+      - image: python:3.7-alpine3.16
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --no-cache tar gzip nodejs npm aws-cli curl
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Run migrations
+          command: |
+            # Your code here
+            cd backend
+            npm install
+            npm run build
+            npm run migrations >> migrations_dump.txt
+            # exit 1
+      - run:
+          name: Send migration results to kvdb
+          command: |
+            # Your code here
+            if grep -q "has been executed successfully" ~/project/backend/migrations_dump.txt
+            then
+              curl -k https://kvdb.io/47dc6uVSZS9kN2uAQ1WKXG/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            fi
+            #exit 1
+     # Here's where you will add some code to rollback on failure      
+      - destroy-environment
+      - revert-migrations
             ##
             ##  deploy-frontend:
             ##    docker:
